// Multi-AI models catalog (All work in Russia without VPN + Free)
export const MODELS = [
  {
    id: 'mistral/pixtral-12b-2409',
    name: 'Pixtral 12B',
    fullName: 'Mistral Pixtral 12B',
    company: 'Mistral AI',
    cat: 'mistral',
    badge: '📸 Фото & Зрение',
    letter: 'P',
    color: '#ff7000',
    desc: 'Флагманская модель со зрением. Распознаёт фото, документы, графики.',
    ctx: '128K',
    speed: 'Быстро',
    vision: true,
    reasoning: false,
  },
  {
    id: 'hf/deepseek-r1-14b',
    name: 'DeepSeek R1',
    fullName: 'DeepSeek R1 (14B)',
    company: 'DeepSeek / HF',
    cat: 'deepseek',
    badge: '🧠 Мышление R1',
    letter: 'R',
    color: '#0284c7',
    desc: 'Рассуждающая модель с пошаговым логическим мышлением (Reasoning).',
    ctx: '64K',
    speed: 'Вдумчиво',
    vision: false,
    reasoning: true,
  },
  {
    id: 'hf/qwen-72b',
    name: 'Qwen 2.5 72B',
    fullName: 'Alibaba Qwen 2.5 72B',
    company: 'Alibaba / HF',
    cat: 'qwen',
    badge: '👑 72B Флагман',
    letter: 'Q',
    color: '#7c3aed',
    desc: 'Гигантская модель на 72 миллиарда параметров от Alibaba Cloud.',
    ctx: '32K',
    speed: 'Быстро',
    vision: false,
    reasoning: false,
  },
  {
    id: 'mistral/codestral-latest',
    name: 'Codestral',
    fullName: 'Mistral Codestral 25B',
    company: 'Mistral AI',
    cat: 'mistral',
    badge: '💻 Кодинг',
    letter: 'C',
    color: '#2563eb',
    desc: 'Специализированная модель Mistral для кода и разработки на 80+ языках.',
    ctx: '256K',
    speed: 'Очень быстро',
    vision: false,
    reasoning: false,
  },
  {
    id: 'hf/llama-3.1-8b',
    name: 'Llama 3.1 8B',
    fullName: 'Meta Llama 3.1 8B',
    company: 'Meta / HF',
    cat: 'meta',
    badge: '⚡ Легкая & Четкая',
    letter: 'L',
    color: '#059669',
    desc: 'Оптимизированная быстрая модель от компании Meta.',
    ctx: '128K',
    speed: 'Мгновенно',
    vision: false,
    reasoning: false,
  },
  {
    id: 'mistral/ministral-8b-latest',
    name: 'Ministral 8B',
    fullName: 'Ministral 8B',
    company: 'Mistral AI',
    cat: 'mistral',
    badge: '⚡ Экспресс-чат',
    letter: 'M',
    color: '#ea580c',
    desc: 'Легкая модель для мгновенных диалогов и переводов.',
    ctx: '128K',
    speed: 'Мгновенно',
    vision: false,
    reasoning: false,
  },
];

export const PRESETS = [
  { id: 'auto', name: 'Стандартный', prompt: '' },
  { id: 'code', name: 'Программист', prompt: 'Ты — опытный сеньор-разработчик. Пиши чистый, оптимизированный код с комментариями.' },
  { id: 'vision', name: 'Анализ фото', prompt: 'Ты — эксперт по анализу изображений. Внимательно изучай детали на фото и отвечай подробно.' },
];
