// Multi-AI models catalog (All work in Russia without VPN + Free)
export const MODELS = [
  {
    id: 'mistral/pixtral-12b-2409',
    name: 'Pixtral 12B',
    fullName: 'Mistral Pixtral 12B',
    company: 'Mistral AI',
    cat: 'mistral',
    badge: '📸 Фото & Зрение',
    letter: 'P',
    color: '#ff7000',
    desc: 'Флагманская модель со зрением. Распознаёт фото задач, документы, графики.',
    ctx: '128K',
    speed: 'Быстро',
    vision: true,
    reasoning: false,
  },
  {
    id: 'image/nano-banana',
    name: 'Nano Banana 🍌',
    fullName: 'Nano Banana 2.0 Ultra HD',
    company: 'Nano Banana AI',
    cat: 'image',
    badge: '🍌 Нано Банана 2.0',
    letter: 'B',
    color: '#eab308',
    desc: 'Новейшая продвинутая нейросеть для фотореалистичных 4K артов, иллюстраций к урокам и концептов без водяных знаков.',
    ctx: '4K Ultra',
    speed: 'Быстро',
    vision: false,
    reasoning: false,
    imageGen: true,
  },
  {
    id: 'hf/deepseek-r1-14b',
    name: 'DeepSeek R1',
    fullName: 'DeepSeek R1 (14B Reasoning)',
    company: 'DeepSeek AI',
    cat: 'deepseek',
    badge: '🧠 Мышление R1',
    letter: 'R',
    color: '#0284c7',
    desc: 'Рассуждающая модель с пошаговым логическим мышлением и разбором сложных задач.',
    ctx: '64K',
    speed: 'Вдумчиво',
    vision: false,
    reasoning: true,
  },
  {
    id: 'hf/llama-3.3-70b',
    name: 'Llama 3.3 70B',
    fullName: 'Meta Llama 3.3 70B Instruct',
    company: 'Meta AI',
    cat: 'meta',
    badge: '👑 70B Флагман Meta',
    letter: 'L',
    color: '#10b981',
    desc: 'Сверхмощный флагман Meta на 70 миллиардов параметров с глубокими знаниями.',
    ctx: '128K',
    speed: 'Быстро',
    vision: false,
    reasoning: false,
  },
  {
    id: 'hf/qwen-72b',
    name: 'Qwen 2.5 72B',
    fullName: 'Alibaba Qwen 2.5 72B',
    company: 'Alibaba Cloud',
    cat: 'qwen',
    badge: '🏆 72B Гигант',
    letter: 'Q',
    color: '#7c3aed',
    desc: 'Гигантская модель на 72 миллиарда параметров от Alibaba для сложных текстов и точных наук.',
    ctx: '32K',
    speed: 'Быстро',
    vision: false,
    reasoning: false,
  },
  {
    id: 'mistral/codestral-latest',
    name: 'Codestral 25B',
    fullName: 'Mistral Codestral 25B',
    company: 'Mistral AI',
    cat: 'mistral',
    badge: '💻 Кодинг & IT',
    letter: 'C',
    color: '#2563eb',
    desc: 'Специализированная модель для программирования, алгоритмов и информатики.',
    ctx: '256K',
    speed: 'Очень быстро',
    vision: false,
    reasoning: false,
  },
  {
    id: 'hf/gemma-3-4b',
    name: 'Gemma 3',
    fullName: 'Google Gemma 3 (IT)',
    company: 'Google',
    cat: 'google',
    badge: '⚡ Google AI',
    letter: 'G',
    color: '#ea4335',
    desc: 'Умная компактная модель от исследователей Google DeepMind.',
    ctx: '32K',
    speed: 'Мгновенно',
    vision: false,
    reasoning: false,
  },
  {
    id: 'hf/llama-3.1-8b',
    name: 'Llama 3.1 8B',
    fullName: 'Meta Llama 3.1 8B',
    company: 'Meta AI',
    cat: 'meta',
    badge: '⚡ Легкая & Четкая',
    letter: 'L',
    color: '#059669',
    desc: 'Оптимизированная быстрая модель для простых школьных вопросов и переводов.',
    ctx: '128K',
    speed: 'Мгновенно',
    vision: false,
    reasoning: false,
  },
  {
    id: 'mistral/ministral-8b-latest',
    name: 'Ministral 8B',
    fullName: 'Ministral 8B',
    company: 'Mistral AI',
    cat: 'mistral',
    badge: '🚀 Экспресс-чат',
    letter: 'M',
    color: '#ea580c',
    desc: 'Легкая модель от Mistral для моментальных ответов за доли секунды.',
    ctx: '128K',
    speed: 'Мгновенно',
    vision: false,
    reasoning: false,
  },
];

export const PRESETS = [
  { id: 'auto', name: 'Стандартный', prompt: '' },
  { id: 'code', name: 'Программист', prompt: 'Ты — опытный сеньор-разработчик. Пиши чистый, оптимизированный код с комментариями.' },
  { id: 'vision', name: 'Анализ фото', prompt: 'Ты — эксперт по анализу изображений. Внимательно изучай детали на фото и отвечай подробно.' },
  { id: 'art', name: 'Художник', prompt: 'Ты — креативный иллюстратор. Создавай подробные и красивые визуальные концепции.' },
];
